describe('Los estudiantes login', function() {
    it('Visits los estudiantes and fails when creating an already existing account', function() {
		cy.visit('https://losestudiantes.co')
		cy.contains('Cerrar').click()
		cy.contains('Ingresar').click()
		cy.get('.cajaSignUp').find('input[name="nombre"]').click().type("carlos")
		cy.get('.cajaSignUp').find('input[name="apellido"]').click().type("ramirez")
		cy.get('.cajaSignUp').find('input[name="correo"]').click().type("j.arias915@uniandes.edu.co")
		cy.get('.cajaSignUp').find('select[name="idUniversidad"]').select("universidad-de-los-andes")
		cy.get('.cajaSignUp').find('select[name="idDepartamento"]').select("2")
		cy.get('.cajaSignUp').find('input[name="password"]').click().type("pwd2017")
		cy.get('.cajaSignUp').find('input[name="acepta"]').check().should('be.checked')
		cy.get('.cajaSignUp').contains('Registrarse').click()
		cy.contains("Error: Ya existe un usuario registrado con el correo 'j.arias915@uniandes.edu.co'")
    })
})